name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Theos Environment
      uses: Randomblock1/theos-action@v1
      with:
        theos-sdks: 'https://github.com/theos/sdks'

    - name: Build Package
      run: |
        make package
